threshold = {
    "pe_ratio": {
        "low": 15,
        "mid": 30,
    },
    "debt_to_equity": {
        "low": 0.5,
        "mid": 1,
    },
    "beta": {
        "low": 0.75,
        "mid": 1,
    },
    "profit_growth": {  # >
        "low": 15,
        "mid": 5,
    },
    "sales_growth": {  # >
        "low": 15,
        "mid": 5,
    },
}

risk_weights = {"low": 1, "mid": 2, "high": 3}
cal_risk_range_min, cal_risk_range_max = 170, 1500
acl_risk_range_min, acl_risk_range_max = 0, 1000
convert_range = lambda computed_risk: (
    (computed_risk - cal_risk_range_min)
    / (cal_risk_range_max - cal_risk_range_min)
    * (acl_risk_range_max - acl_risk_range_min)
    + acl_risk_range_min
)

fundamental_data = {
    "TATACONSUM": {
        "debt_to_equity": 0.09,
        "beta": 0.8,
        "pe_ratio": 87.6,
        "profit_growth": 21.4,
        "sales_growth": 11.7,
        "promoter_holding": 33.6,
    },
    "WIPRO": {
        "debt_to_equity": 0.26,
        "beta": 1.23,
        "pe_ratio": 24.7,
        "profit_growth": -0.56,
        "sales_growth": 2.93,
        "promoter_holding": 72.9,
    },
    "TECHM": {
        "debt_to_equity": 0.1,
        "beta": 1.10,
        "pe_ratio": 45.1,
        "profit_growth": -46,
        "sales_growth": 2.23,
        "promoter_holding": 35.1,
    },
    "HINDUNILVR": {
        "debt_to_equity": 0.03,
        "beta": 0.57,
        "pe_ratio": 54.8,
        "profit_growth": 4.27,
        "sales_growth": 4.68,
        "promoter_holding": 61.9,
    },
    "NESTLEIND": {
        "debt_to_equity": 0.11,
        "beta": 0.49,
        "pe_ratio": 82.9,
        "profit_growth": 25.9,
        "sales_growth": 13.2,
        "promoter_holding": 62.8,
    },
    "TITAN": {
        "debt_to_equity": 1.15,
        "beta": 0.62,
        "pe_ratio": 93.2,
        "profit_growth": 12.6,
        "sales_growth": 28.8,
        "promoter_holding": 52.9,
    },
    "TCS": {
        "debt_to_equity": 0.08,
        "beta": 0.88,
        "pe_ratio": 31.8,
        "profit_growth": 12.0,
        "sales_growth": 10.1,
        "promoter_holding": 72.4,
    },
    "INFY": {
        "debt_to_equity": 0.11,
        "beta": 1.29,
        "pe_ratio": 28.2,
        "profit_growth": 3.12,
        "sales_growth": 8.18,
        "promoter_holding": 14.8,
    },
    "BAJAJFINSV": {
        "debt_to_equity": 4.94,
        "beta": 0.99,
        "pe_ratio": 33.0,
        "profit_growth": 30.1,
        "sales_growth": 31.9,
        "promoter_holding": 60.7,
    },
    "CIPLA": {
        "debt_to_equity": 0.04,
        "beta": 0.17,
        "pe_ratio": 30.1,
        "profit_growth": 48.1,
        "sales_growth": 13.8,
        "promoter_holding": 33.5,
    },
    "HCLTECH": {
        "debt_to_equity": 0.08,
        "beta": 1.01,
        "pe_ratio": 28.5,
        "profit_growth": 8.56,
        "sales_growth": 10.8,
        "promoter_holding": 60.8,
    },
    "BAJAJ-AUTO": {
        "debt_to_equity": 0.0,
        "beta": 0.62,
        "pe_ratio": 32.4,
        "profit_growth": 31.3,
        "sales_growth": 19.0,
        "promoter_holding": 54.9,
    },
    "ASIANPAINT": {
        "debt_to_equity": 0.14,
        "beta": 0.54,
        "pe_ratio": 50.4,
        "profit_growth": 42.8,
        "sales_growth": 5.83,
        "promoter_holding": 52.6,
    },
    "HEROMOTOCO": {
        "debt_to_equity": 0.04,
        "beta": 0.85,
        "pe_ratio": 24.2,
        "profit_growth": 43.0,
        "sales_growth": 10.2,
        "promoter_holding": 34.8,
    },
    "POWERGRID": {
        "debt_to_equity": 1.38,
        "beta": 0.56,
        "pe_ratio": 17.0,
        "profit_growth": 4.86,
        "sales_growth": 4.83,
        "promoter_holding": 51.3,
    },
    "ULTRACEMCO": {
        "debt_to_equity": 0.20,
        "beta": 0.57,
        "pe_ratio": 44.7,
        "profit_growth": 9.57,
        "sales_growth": 14.6,
        "promoter_holding": 60.0,
    },
    "MARUTI": {
        "debt_to_equity": 0.01,
        "beta": 0.67,
        "pe_ratio": 29.6,
        "profit_growth": 64.0,
        "sales_growth": 20.3,
        "promoter_holding": 58.2,
    },
    "SHREECEM": {
        "debt_to_equity": 0.11,
        "beta": 0.68,
        "pe_ratio": 40.0,
        "profit_growth": 64.9,
        "sales_growth": 19.3,
        "promoter_holding": 62.6,
    },
    "DRREDDY": {
        "debt_to_equity": 0.05,
        "beta": 0.53,
        "pe_ratio": 20.5,
        "profit_growth": 43.5,
        "sales_growth": 14.2,
        "promoter_holding": 26.6,
    },
    "EICHERMOT": {
        "debt_to_equity": 0.03,
        "beta": 0.93,
        "pe_ratio": 28.2,
        "profit_growth": 46.5,
        "sales_growth": 16.3,
        "promoter_holding": 49.2,
    },
    "BRITANNIA": {
        "debt_to_equity": 0.98,
        "beta": 0.53,
        "pe_ratio": 54.7,
        "profit_growth": 17.8,
        "sales_growth": 5.66,
        "promoter_holding": 50.6,
    },
    "BAJFINANCE": {
        "debt_to_equity": 4.28,
        "beta": 0.98,
        "pe_ratio": 29.8,
        "profit_growth": 28.0,
        "sales_growth": 32.9,
        "promoter_holding": 54.8,
    },
    "DIVISLAB": {
        "debt_to_equity": 0.0,
        "beta": 0.62,
        "pe_ratio": 68.7,
        "profit_growth": -42.3,
        "sales_growth": -10.1,
        "promoter_holding": 51.9,
    },
    "KOTAKBANK": {
        "debt_to_equity": 3.75,
        "beta": 1.01,
        "pe_ratio": 19.4,
        "profit_growth": 22.4,
        "sales_growth": 36.0,
        "promoter_holding": 25.9,
    },
    "SUNPHARMA": {
        "debt_to_equity": 0.03,
        "beta": 0.39,
        "pe_ratio": 39.9,
        "profit_growth": 16.4,
        "sales_growth": 11.9,
        "promoter_holding": 54.5,
    },
    "BPCL": {
        "debt_to_equity": 0.79,
        "beta": 0.92,
        "pe_ratio": 4.47,
        "profit_growth": 2007,
        "sales_growth": -2.07,
        "promoter_holding": 53.0,
    },
    "ICICIBANK": {
        "debt_to_equity": 6.53,
        "beta": 0.87,
        "pe_ratio": 17.4,
        "profit_growth": 33.0,
        "sales_growth": 35.6,
        "promoter_holding": 0.0,
    },
    "SBILIFE": {
        "debt_to_equity": 0.0,
        "beta": 0.97,
        "pe_ratio": 83.5,
        "profit_growth": 15.1,
        "sales_growth": 46.3,
        "promoter_holding": 55.4,
    },
    "RELIANCE": {
        "debt_to_equity": 0.42,
        "beta": 1.21,
        "pe_ratio": 28.8,
        "profit_growth": 10.4,
        "sales_growth": 0.57,
        "promoter_holding": 50.3,
    },
    "HDFCLIFE": {
        "debt_to_equity": 0.07,
        "beta": 0.77,
        "pe_ratio": 81.4,
        "profit_growth": 0.79,
        "sales_growth": 41.1,
        "promoter_holding": 50.4,
    },
    "AXISBANK": {
        "debt_to_equity": 8.88,
        "beta": 0.93,
        "pe_ratio": 13.0,
        "profit_growth": 25.3,
        "sales_growth": 32.2,
        "promoter_holding": 8.20,
    },
    "GRASIM": {
        "debt_to_equity": 1.47,
        "beta": 1.0,
        "pe_ratio": 26.0,
        "profit_growth": -30.0,
        "sales_growth": 12.2,
        "promoter_holding": 43.1,
    },
    "SBIN": {
        "debt_to_equity": 13.9,
        "beta": 1.18,
        "pe_ratio": 9.84,
        "profit_growth": 46.1,
        "sales_growth": 28.2,
        "promoter_holding": 57.5,
    },
    "ITC": {
        "debt_to_equity": 0.0,
        "beta": 0.77,
        "pe_ratio": 24.9,
        "profit_growth": 12.4,
        "sales_growth": 1.05,
        "promoter_holding": 0.0,
    },
    "HDFCBANK": {
        "debt_to_equity": 7.39,
        "beta": 1.27,
        "pe_ratio": 15.9,
        "profit_growth": 34.6,
        "sales_growth": 28.6,
        "promoter_holding": 0.0,
    },
    "HINDALCO": {
        "debt_to_equity": 0.59,
        "beta": 1.27,
        "pe_ratio": 12.1,
        "profit_growth": -20.0,
        "sales_growth": -3.26,
        "promoter_holding": 34.6,
    },
    "TATASTEEL": {
        "debt_to_equity": 1.01,
        "beta": 1.26,
        "pe_ratio": 92.0,
        "profit_growth": -89.0,
        "sales_growth": -6.52,
        "promoter_holding": 33.2,
    },
    "ONGC": {
        "debt_to_equity": 0.46,
        "beta": 1.09,
        "pe_ratio": 7.41,
        "profit_growth": 17.2,
        "sales_growth": -5.38,
        "promoter_holding": 58.9,
    },
    "BHARTIARTL": {
        "debt_to_equity": 2.81,
        "beta": 0.66,
        "pe_ratio": 57.2,
        "profit_growth": 56.8,
        "sales_growth": 10.2,
        "promoter_holding": 54.6,
    },
    "IOC": {
        "debt_to_equity": 0.69,
        "beta": 0.94,
        "pe_ratio": 5.36,
        "profit_growth": 534,
        "sales_growth": -3.89,
        "promoter_holding": 51.5,
    },
    "NTPC": {
        "debt_to_equity": 1.45,
        "beta": 1.05,
        "pe_ratio": 16.8,
        "profit_growth": 13.3,
        "sales_growth": 3.60,
        "promoter_holding": 51.1,
    },
    "INDUSINDBK": {
        "debt_to_equity": 7.06,
        "beta": 1.17,
        "pe_ratio": 13.2,
        "profit_growth": 28.8,
        "sales_growth": 27.4,
        "promoter_holding": 15.8,
    },
    "COALINDIA": {
        "debt_to_equity": 0.09,
        "beta": 1.09,
        "pe_ratio": 9.29,
        "profit_growth": 0.17,
        "sales_growth": 7.72,
        "promoter_holding": 63.1,
    },
    "TATAMOTORS": {
        "debt_to_equity": 2.38,
        "beta": 1.10,
        "pe_ratio": 17.0,
        "profit_growth": 496,
        "sales_growth": 33.1,
        "promoter_holding": 46.4,
    },
    "ADANIPORTS": {
        "debt_to_equity": 1.03,
        "beta": 1.44,
        "pe_ratio": 32.8,
        "profit_growth": 67.6,
        "sales_growth": 33.4,
        "promoter_holding": 65.9,
    },
    "JSWSTEEL": {
        "debt_to_equity": 1.11,
        "beta": 1.10,
        "pe_ratio": 18.3,
        "profit_growth": 196,
        "sales_growth": 5.91,
        "promoter_holding": 44.8,
    },
    "KPITTECH": {
        "debt_to_equity": 0.20,
        "beta": 0.68,
        "pe_ratio": 80.7,
        "profit_growth": 54.2,
        "sales_growth": 52.4,
        "promoter_holding": 39.5,
    },
    "EXIDEIND": {
        "debt_to_equity": 0.06,
        "beta": 0.93,
        "pe_ratio": 32.0,
        "profit_growth": 11.5,
        "sales_growth": 9.04,
        "promoter_holding": 46.0,
    },
    "NATIONALUM": {
        "debt_to_equity": 0.01,
        "beta": 1.94,
        "pe_ratio": 18.4,
        "profit_growth": -23.6,
        "sales_growth": -11.3,
        "promoter_holding": 51.3,
    },
    "KARURVYASA": {
        "debt_to_equity": 9.09,
        "beta": 0.77,
        "pe_ratio": 9.66,
        "profit_growth": 51.4,
        "sales_growth": 26.5,
        "promoter_holding": 2.22,
    },
    "SULA": {
        "debt_to_equity": 0.47,
        "beta": 0.48,
        "pe_ratio": 48.2,
        "profit_growth": 16.4,
        "sales_growth": 12.9,
        "promoter_holding": 26.3,
    },
    "IEX": {
        "debt_to_equity": 0.01,
        "beta": 1.27,
        "pe_ratio": 39.8,
        "profit_growth": 13.2,
        "sales_growth": 7.23,
        "promoter_holding": 0.0,
    },
    "EASEMYTRIP": {
        "debt_to_equity": 0.19,
        "beta": 0.83,
        "pe_ratio": 51.3,
        "profit_growth": 25.3,
        "sales_growth": 22.6,
        "promoter_holding": 64.3,
    },
    "CUB": {
        "debt_to_equity": 7.66,
        "beta": 1.18,
        "pe_ratio": 10.1,
        "profit_growth": 5.45,
        "sales_growth": 13.0,
        "promoter_holding": 0.0,
    },
    "DABUR": {
        "debt_to_equity":0.16 ,
        "beta": 0.78,
        "pe_ratio": 53.9,
        "profit_growth": -0.06,
        "sales_growth": 7.89,
        "promoter_holding": 66.2,
    },
     "TATACONSUM": {
        "debt_to_equity":0.09 ,
        "beta": 0.79,
        "pe_ratio": 87.0,
        "profit_growth": 21.4,
        "sales_growth": 11.7,
        "promoter_holding": 33.6,
    },
     "VEDL": {
        "debt_to_equity": 2.38,
        "beta": 1.16,
        "pe_ratio": 19.6,
        "profit_growth": -64.8,
        "sales_growth": -2.04,
        "promoter_holding": 63.7,
    },

}
