# Generated by Django 4.1.13 on 2024-02-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('buy_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('profit_loss', models.FloatField()),
                ('sector', models.CharField(max_length=100)),
                ('invested_value', models.FloatField()),
            ],
        ),
    ]
